version: '2'

services:
  postfix:
    image: instrumentisto/postfix:3
    restart: unless-stopped
    volumes:
    - ./config/postfix:/etc/postfix/main.cf.d
    - ./config/mailman-core:/opt/mailman
    ports:
    - "25:25"

  mailman-core:
    image: maxking/mailman-core:0.4
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
    - ./config/mailman-core:/opt/mailman/
    depends_on:
    - database
    environment:
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - DATABASE_TYPE=postgres
    - DATABASE_CLASS=mailman.database.postgresql.PostgreSQLDatabase
    - HYPERKITTY_API_KEY=someapikey
    - MTA=postfix
    - SMTP_HOST=postfix

  mailman-web:
    image: maxking/mailman-web:0.4
    restart: unless-stopped
    depends_on:
    - mailman-core
    - database
    volumes:
    - ./config/mailman-web:/opt/mailman-web-data
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_URL=postgres://mailman:mailmanpass@database/mailmandb
    - HYPERKITTY_API_KEY=someapikey
    - SERVE_FROM_DOMAIN=lists.fablab-karlsruhe.de
    - SECRET_KEY=supersecretdjangokey
    - UWSGI_STATIC_MAP=/static=/opt/mailman-web-data/static
    - SMTP_HOST=postfix
    - LETSENCRYPT_EMAIL=mail@morbi-happens.de
    - LETSENCRYPT_HOST=lists.fablab-karlsruhe.de
    - VIRTUAL_HOST=lists.fablab-karlsruhe.de
    - VIRTUAL_PORT=8000

  database:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: mailmandb
      POSTGRES_USER: mailman
      POSTGRES_PASSWORD: mailmanpass
    volumes:
    - ./data/postgres:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/certs:/etc/nginx/certs:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d:rw
      - ./data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./data/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx-proxy
    volumes:
      - ./data/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
